name: Deploy to VPS

on:
  push:
    branches:
      - main   # chỉ deploy khi push vào main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 -d > id_ed25519
          chmod 600 id_ed25519
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/ngocminhwood.com
            git reset --hard
            git pull origin main
            # Nếu dùng npm/yarn build thì chạy thêm:
            # npm install && npm run build
            systemctl restart nginx || true
          EOF
