name: Deploy NgocMinhWood Website

on:
  push:
    branches:
      - main   # Mỗi lần bạn push code lên nhánh main thì auto deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: SSH vào VPS và deploy
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Vào thư mục web
            cd /var/www/ngocminhwood.com || exit

            # Nếu chưa clone repo thì clone
            if [ ! -d ".git" ]; then
              git clone git@github-ngocminhwood:jakediep1902/ngocminhwood.git .
            else
              git reset --hard
              git pull origin main
            fi

            # Phân quyền cho web server
            chown -R www-data:www-data /var/www/ngocminhwood.com
            chmod -R 755 /var/www/ngocminhwood.com

            # Restart/reload nginx
            systemctl reload nginx || true
